namespace Proyecto_Gym_ProgramacionIII_Jeovanny
{
    partial class FrmLogin
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmLogin));
            pnlMarca = new Panel();
            pnlMarcaSuperior = new Panel();
            lblMarca = new Label();
            picGimnasio = new PictureBox();
            pnlLogin = new Panel();
            lblMensaje = new Label();
            btnSalir = new Button();
            btnIniciarSesion = new Button();
            chkMostrarContrasena = new CheckBox();
            txtContrasena = new TextBox();
            lblContrasena = new Label();
            txtUsuario = new TextBox();
            lblUsuario = new Label();
            lblInstruccion = new Label();
            lblBienvenida = new Label();
            pnlMarca.SuspendLayout();
            pnlMarcaSuperior.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picGimnasio).BeginInit();
            pnlLogin.SuspendLayout();
            SuspendLayout();
            pnlMarca.BackColor = Color.Black;
            pnlMarca.Controls.Add(picGimnasio);
            pnlMarca.Controls.Add(pnlMarcaSuperior);
            pnlMarca.Dock = DockStyle.Left;
            pnlMarca.Location = new Point(0, 0);
            pnlMarca.Name = "pnlMarca";
            pnlMarca.Size = new Size(360, 540);
            pnlMarca.TabIndex = 0;
            pnlMarcaSuperior.BackColor = Color.Black;
            pnlMarcaSuperior.Controls.Add(lblMarca);
            pnlMarcaSuperior.Dock = DockStyle.Top;
            pnlMarcaSuperior.Location = new Point(0, 0);
            pnlMarcaSuperior.Name = "pnlMarcaSuperior";
            pnlMarcaSuperior.Size = new Size(360, 105);
            pnlMarcaSuperior.TabIndex = 0;
            lblMarca.Dock = DockStyle.Fill;
            lblMarca.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
            lblMarca.ForeColor = Color.White;
            lblMarca.Location = new Point(0, 0);
            lblMarca.Name = "lblMarca";
            lblMarca.Size = new Size(360, 105);
            lblMarca.TabIndex = 0;
            lblMarca.Text = "Super Saija Gym";
            lblMarca.TextAlign = ContentAlignment.MiddleCenter;
            picGimnasio.BackColor = Color.Black;
            picGimnasio.BorderStyle = BorderStyle.None;
            picGimnasio.Dock = DockStyle.Fill;
            picGimnasio.Image = (Image)resources.GetObject("picGimnasio.Image");
            picGimnasio.Location = new Point(0, 105);
            picGimnasio.Margin = new Padding(0);
            picGimnasio.Name = "picGimnasio";
            picGimnasio.Size = new Size(360, 435);
            picGimnasio.SizeMode = PictureBoxSizeMode.Zoom;
            picGimnasio.TabIndex = 1;
            picGimnasio.TabStop = false;
            pnlLogin.BackColor = Color.White;
            pnlLogin.Controls.Add(lblMensaje);
            pnlLogin.Controls.Add(btnSalir);
            pnlLogin.Controls.Add(btnIniciarSesion);
            pnlLogin.Controls.Add(chkMostrarContrasena);
            pnlLogin.Controls.Add(txtContrasena);
            pnlLogin.Controls.Add(lblContrasena);
            pnlLogin.Controls.Add(txtUsuario);
            pnlLogin.Controls.Add(lblUsuario);
            pnlLogin.Controls.Add(lblInstruccion);
            pnlLogin.Controls.Add(lblBienvenida);
            pnlLogin.Dock = DockStyle.Fill;
            pnlLogin.Location = new Point(360, 0);
            pnlLogin.Name = "pnlLogin";
            pnlLogin.Size = new Size(560, 540);
            pnlLogin.TabIndex = 1;
            lblMensaje.AutoSize = false;
            lblMensaje.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            lblMensaje.ForeColor = Color.Black;
            lblMensaje.Location = new Point(68, 474);
            lblMensaje.Name = "lblMensaje";
            lblMensaje.Size = new Size(424, 44);
            lblMensaje.TabIndex = 9;
            lblMensaje.TextAlign = ContentAlignment.MiddleLeft;
            btnSalir.BackColor = Color.White;
            btnSalir.Cursor = Cursors.Hand;
            btnSalir.FlatAppearance.BorderColor = Color.Black;
            btnSalir.FlatStyle = FlatStyle.Flat;
            btnSalir.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnSalir.ForeColor = Color.Black;
            btnSalir.Location = new Point(68, 420);
            btnSalir.Name = "btnSalir";
            btnSalir.Size = new Size(424, 40);
            btnSalir.TabIndex = 4;
            btnSalir.Text = "SALIR";
            btnSalir.UseVisualStyleBackColor = false;
            btnSalir.Click += btnSalir_Click;
            btnIniciarSesion.BackColor = Color.FromArgb(124, 142, 163);
            btnIniciarSesion.Cursor = Cursors.Hand;
            btnIniciarSesion.FlatAppearance.BorderSize = 0;
            btnIniciarSesion.FlatStyle = FlatStyle.Flat;
            btnIniciarSesion.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnIniciarSesion.ForeColor = Color.White;
            btnIniciarSesion.Location = new Point(68, 362);
            btnIniciarSesion.Name = "btnIniciarSesion";
            btnIniciarSesion.Size = new Size(424, 44);
            btnIniciarSesion.TabIndex = 3;
            btnIniciarSesion.Text = "INICIAR SESIÓN";
            btnIniciarSesion.UseVisualStyleBackColor = false;
            btnIniciarSesion.Click += btnIniciarSesion_Click;
            chkMostrarContrasena.AutoSize = true;
            chkMostrarContrasena.BackColor = Color.White;
            chkMostrarContrasena.Cursor = Cursors.Hand;
            chkMostrarContrasena.Font = new Font("Segoe UI", 9.5F);
            chkMostrarContrasena.ForeColor = Color.Black;
            chkMostrarContrasena.Location = new Point(68, 320);
            chkMostrarContrasena.Name = "chkMostrarContrasena";
            chkMostrarContrasena.Size = new Size(145, 21);
            chkMostrarContrasena.TabIndex = 2;
            chkMostrarContrasena.Text = "Mostrar contraseña";
            chkMostrarContrasena.UseVisualStyleBackColor = false;
            chkMostrarContrasena.CheckedChanged += chkMostrarContrasena_CheckedChanged;
            txtContrasena.BackColor = Color.White;
            txtContrasena.BorderStyle = BorderStyle.FixedSingle;
            txtContrasena.Font = new Font("Segoe UI", 11F);
            txtContrasena.ForeColor = Color.Black;
            txtContrasena.Location = new Point(68, 274);
            txtContrasena.MaxLength = 100;
            txtContrasena.Name = "txtContrasena";
            txtContrasena.PlaceholderText = "Escribe tu contraseña";
            txtContrasena.Size = new Size(424, 27);
            txtContrasena.TabIndex = 1;
            txtContrasena.UseSystemPasswordChar = true;
            lblContrasena.AutoSize = true;
            lblContrasena.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            lblContrasena.ForeColor = Color.Black;
            lblContrasena.Location = new Point(68, 248);
            lblContrasena.Name = "lblContrasena";
            lblContrasena.Size = new Size(81, 17);
            lblContrasena.TabIndex = 5;
            lblContrasena.Text = "Contraseña";
            txtUsuario.BackColor = Color.White;
            txtUsuario.BorderStyle = BorderStyle.FixedSingle;
            txtUsuario.CharacterCasing = CharacterCasing.Normal;
            txtUsuario.Font = new Font("Segoe UI", 11F);
            txtUsuario.ForeColor = Color.Black;
            txtUsuario.Location = new Point(68, 196);
            txtUsuario.MaxLength = 50;
            txtUsuario.Name = "txtUsuario";
            txtUsuario.PlaceholderText = "Escribe tu usuario";
            txtUsuario.Size = new Size(424, 27);
            txtUsuario.TabIndex = 0;
            lblUsuario.AutoSize = true;
            lblUsuario.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            lblUsuario.ForeColor = Color.Black;
            lblUsuario.Location = new Point(68, 170);
            lblUsuario.Name = "lblUsuario";
            lblUsuario.Size = new Size(126, 17);
            lblUsuario.TabIndex = 3;
            lblUsuario.Text = "Nombre de usuario";
            lblInstruccion.AutoSize = true;
            lblInstruccion.Font = new Font("Segoe UI", 11F);
            lblInstruccion.ForeColor = Color.FromArgb(124, 142, 163);
            lblInstruccion.Location = new Point(68, 124);
            lblInstruccion.Name = "lblInstruccion";
            lblInstruccion.Size = new Size(190, 20);
            lblInstruccion.TabIndex = 1;
            lblInstruccion.Text = "Inicia sesión para continuar";
            lblBienvenida.AutoSize = true;
            lblBienvenida.Font = new Font("Segoe UI", 28F, FontStyle.Bold);
            lblBienvenida.ForeColor = Color.Black;
            lblBienvenida.Location = new Point(64, 65);
            lblBienvenida.Name = "lblBienvenida";
            lblBienvenida.Size = new Size(220, 51);
            lblBienvenida.TabIndex = 0;
            lblBienvenida.Text = "Bienvenido";
            AcceptButton = btnIniciarSesion;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            CancelButton = btnSalir;
            ClientSize = new Size(920, 540);
            Controls.Add(pnlLogin);
            Controls.Add(pnlMarca);
            Font = new Font("Segoe UI", 9F);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            MinimizeBox = true;
            Name = "FrmLogin";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Inicio de sesión - Super Saija Gym";
            pnlMarca.ResumeLayout(false);
            pnlMarcaSuperior.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picGimnasio).EndInit();
            pnlLogin.ResumeLayout(false);
            pnlLogin.PerformLayout();
            ResumeLayout(false);
        }

        private Panel pnlMarca;
        private Panel pnlMarcaSuperior;
        private Label lblMarca;
        private PictureBox picGimnasio;
        private Panel pnlLogin;
        private Label lblBienvenida;
        private Label lblInstruccion;
        private Label lblUsuario;
        private TextBox txtUsuario;
        private Label lblContrasena;
        private TextBox txtContrasena;
        private CheckBox chkMostrarContrasena;
        private Button btnIniciarSesion;
        private Button btnSalir;
        private Label lblMensaje;
    }
}
