namespace Proyecto_Gym_ProgramacionIII_Jeovanny.Formularios
{
    partial class FrmPrincipal
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pnlMenuLateral;
        private Label lblNombreSistema;
        private FlowLayoutPanel pnlOpciones;
        private Button btnInicio;
        private Button btnMantenimientos;
        private FlowLayoutPanel pnlSubmenuMantenimientos;
        private Button btnClientes;
        private Button btnEntrenadores;
        private Button btnTiposMembresias;
        private Button btnClasesActividades;
        private Button btnHorariosClases;
        private Button btnCategoriasProductos;
        private Button btnProductos;
        private Button btnProveedores;
        private Button btnConsultas;
        private FlowLayoutPanel pnlSubmenuConsultas;
        private Button btnConsultaEntrenadores;
        private Button btnConsultaTiposMembresias;
        private Button btnConsultaClases;
        private Button btnConsultaReservas;
        private Button btnConsultaCargos;
        private Button btnConsultaProductos;
        private Button btnConsultaVentas;
        private Button btnConsultaCompras;
        private Button btnConsultaProveedores;
        private Button btnConsultaCobros;
        private Panel pnlSesion;
        private TableLayoutPanel tlpBotonesSesion;
        private Label lblBienvenida;
        private Label lblRol;
        private Button btnCerrarSesion;
        private Button btnSalir;
        private Panel pnlContenido;
        private PictureBox picInicio;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            pnlMenuLateral = new Panel();
            pnlOpciones = new FlowLayoutPanel();
            btnInicio = new Button();
            btnMantenimientos = new Button();
            pnlSubmenuMantenimientos = new FlowLayoutPanel();
            btnClientes = new Button();
            btnEntrenadores = new Button();
            btnTiposMembresias = new Button();
            btnClasesActividades = new Button();
            btnHorariosClases = new Button();
            btnCategoriasProductos = new Button();
            btnProductos = new Button();
            btnProveedores = new Button();
            btnConsultas = new Button();
            pnlSubmenuConsultas = new FlowLayoutPanel();
            btnConsultaEntrenadores = new Button();
            btnConsultaTiposMembresias = new Button();
            btnConsultaClases = new Button();
            btnConsultaReservas = new Button();
            btnConsultaCargos = new Button();
            btnConsultaProductos = new Button();
            btnConsultaVentas = new Button();
            btnConsultaCompras = new Button();
            btnConsultaProveedores = new Button();
            btnConsultaCobros = new Button();
            pnlSesion = new Panel();
            tlpBotonesSesion = new TableLayoutPanel();
            btnCerrarSesion = new Button();
            btnSalir = new Button();
            lblRol = new Label();
            lblBienvenida = new Label();
            lblNombreSistema = new Label();
            pnlContenido = new Panel();
            picInicio = new PictureBox();
            pnlMenuLateral.SuspendLayout();
            pnlOpciones.SuspendLayout();
            pnlSubmenuMantenimientos.SuspendLayout();
            pnlSubmenuConsultas.SuspendLayout();
            pnlSesion.SuspendLayout();
            tlpBotonesSesion.SuspendLayout();
            pnlContenido.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picInicio).BeginInit();
            SuspendLayout();
            pnlMenuLateral.BackColor = Color.Black;
            pnlMenuLateral.Controls.Add(pnlOpciones);
            pnlMenuLateral.Controls.Add(pnlSesion);
            pnlMenuLateral.Controls.Add(lblNombreSistema);
            pnlMenuLateral.Dock = DockStyle.Left;
            pnlMenuLateral.Location = new Point(0, 0);
            pnlMenuLateral.Name = "pnlMenuLateral";
            pnlMenuLateral.Size = new Size(263, 720);
            pnlMenuLateral.TabIndex = 0;
            pnlOpciones.AutoScroll = true;
            pnlOpciones.BackColor = Color.Black;
            pnlOpciones.Controls.Add(btnInicio);
            pnlOpciones.Controls.Add(btnMantenimientos);
            pnlOpciones.Controls.Add(pnlSubmenuMantenimientos);
            pnlOpciones.Controls.Add(btnConsultas);
            pnlOpciones.Controls.Add(pnlSubmenuConsultas);
            pnlOpciones.Dock = DockStyle.Fill;
            pnlOpciones.FlowDirection = FlowDirection.TopDown;
            pnlOpciones.Location = new Point(0, 96);
            pnlOpciones.Name = "pnlOpciones";
            pnlOpciones.Size = new Size(263, 491);
            pnlOpciones.TabIndex = 1;
            pnlOpciones.WrapContents = false;
            btnInicio.BackColor = Color.Black;
            btnInicio.Cursor = Cursors.Hand;
            btnInicio.FlatAppearance.BorderSize = 0;
            btnInicio.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnInicio.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnInicio.FlatStyle = FlatStyle.Flat;
            btnInicio.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnInicio.ForeColor = Color.White;
            btnInicio.Margin = new Padding(0);
            btnInicio.Name = "btnInicio";
            btnInicio.Padding = new Padding(21, 0, 0, 0);
            btnInicio.Size = new Size(263, 44);
            btnInicio.Text = "INICIO";
            btnInicio.TextAlign = ContentAlignment.MiddleLeft;
            btnInicio.UseVisualStyleBackColor = false;
            btnInicio.Click += btnInicio_Click;
            btnMantenimientos.BackColor = Color.Black;
            btnMantenimientos.Cursor = Cursors.Hand;
            btnMantenimientos.FlatAppearance.BorderSize = 0;
            btnMantenimientos.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnMantenimientos.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnMantenimientos.FlatStyle = FlatStyle.Flat;
            btnMantenimientos.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnMantenimientos.ForeColor = Color.White;
            btnMantenimientos.Margin = new Padding(0);
            btnMantenimientos.Name = "btnMantenimientos";
            btnMantenimientos.Padding = new Padding(21, 0, 0, 0);
            btnMantenimientos.Size = new Size(263, 44);
            btnMantenimientos.Text = ">  MANTENIMIENTOS";
            btnMantenimientos.TextAlign = ContentAlignment.MiddleLeft;
            btnMantenimientos.UseVisualStyleBackColor = false;
            btnMantenimientos.Click += btnMantenimientos_Click;
            pnlSubmenuMantenimientos.BackColor = Color.Black;
            pnlSubmenuMantenimientos.Controls.Add(btnClientes);
            pnlSubmenuMantenimientos.Controls.Add(btnEntrenadores);
            pnlSubmenuMantenimientos.Controls.Add(btnTiposMembresias);
            pnlSubmenuMantenimientos.Controls.Add(btnClasesActividades);
            pnlSubmenuMantenimientos.Controls.Add(btnHorariosClases);
            pnlSubmenuMantenimientos.Controls.Add(btnCategoriasProductos);
            pnlSubmenuMantenimientos.Controls.Add(btnProductos);
            pnlSubmenuMantenimientos.Controls.Add(btnProveedores);
            pnlSubmenuMantenimientos.FlowDirection = FlowDirection.TopDown;
            pnlSubmenuMantenimientos.Margin = new Padding(0);
            pnlSubmenuMantenimientos.Name = "pnlSubmenuMantenimientos";
            pnlSubmenuMantenimientos.Size = new Size(263, 320);
            pnlSubmenuMantenimientos.Visible = false;
            pnlSubmenuMantenimientos.WrapContents = false;
            btnClientes.BackColor = Color.Black;
            btnClientes.Cursor = Cursors.Hand;
            btnClientes.FlatAppearance.BorderSize = 0;
            btnClientes.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnClientes.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnClientes.FlatStyle = FlatStyle.Flat;
            btnClientes.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnClientes.ForeColor = Color.White;
            btnClientes.Margin = new Padding(0);
            btnClientes.Name = "btnClientes";
            btnClientes.Padding = new Padding(36, 0, 0, 0);
            btnClientes.Size = new Size(263, 40);
            btnClientes.Text = "CLIENTES";
            btnClientes.TextAlign = ContentAlignment.MiddleLeft;
            btnClientes.UseVisualStyleBackColor = false;
            btnClientes.Click += btnClientes_Click;
            btnEntrenadores.BackColor = Color.Black;
            btnEntrenadores.Cursor = Cursors.Hand;
            btnEntrenadores.FlatAppearance.BorderSize = 0;
            btnEntrenadores.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnEntrenadores.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnEntrenadores.FlatStyle = FlatStyle.Flat;
            btnEntrenadores.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnEntrenadores.ForeColor = Color.White;
            btnEntrenadores.Margin = new Padding(0);
            btnEntrenadores.Name = "btnEntrenadores";
            btnEntrenadores.Padding = new Padding(36, 0, 0, 0);
            btnEntrenadores.Size = new Size(263, 40);
            btnEntrenadores.Text = "ENTRENADORES";
            btnEntrenadores.TextAlign = ContentAlignment.MiddleLeft;
            btnEntrenadores.UseVisualStyleBackColor = false;
            btnEntrenadores.Click += btnEntrenadores_Click;
            btnTiposMembresias.BackColor = Color.Black;
            btnTiposMembresias.Cursor = Cursors.Hand;
            btnTiposMembresias.FlatAppearance.BorderSize = 0;
            btnTiposMembresias.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnTiposMembresias.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnTiposMembresias.FlatStyle = FlatStyle.Flat;
            btnTiposMembresias.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnTiposMembresias.ForeColor = Color.White;
            btnTiposMembresias.Margin = new Padding(0);
            btnTiposMembresias.Name = "btnTiposMembresias";
            btnTiposMembresias.Padding = new Padding(36, 0, 0, 0);
            btnTiposMembresias.Size = new Size(263, 40);
            btnTiposMembresias.Text = "TIPOS DE MEMBRESÍAS";
            btnTiposMembresias.TextAlign = ContentAlignment.MiddleLeft;
            btnTiposMembresias.UseVisualStyleBackColor = false;
            btnTiposMembresias.Click += btnTiposMembresias_Click;
            btnClasesActividades.BackColor = Color.Black;
            btnClasesActividades.Cursor = Cursors.Hand;
            btnClasesActividades.FlatAppearance.BorderSize = 0;
            btnClasesActividades.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnClasesActividades.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnClasesActividades.FlatStyle = FlatStyle.Flat;
            btnClasesActividades.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnClasesActividades.ForeColor = Color.White;
            btnClasesActividades.Margin = new Padding(0);
            btnClasesActividades.Name = "btnClasesActividades";
            btnClasesActividades.Padding = new Padding(36, 0, 0, 0);
            btnClasesActividades.Size = new Size(263, 40);
            btnClasesActividades.Text = "CLASES Y ACTIVIDADES";
            btnClasesActividades.TextAlign = ContentAlignment.MiddleLeft;
            btnClasesActividades.UseVisualStyleBackColor = false;
            btnClasesActividades.Click += btnClasesActividades_Click;
            btnHorariosClases.BackColor = Color.Black;
            btnHorariosClases.Cursor = Cursors.Hand;
            btnHorariosClases.FlatAppearance.BorderSize = 0;
            btnHorariosClases.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnHorariosClases.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnHorariosClases.FlatStyle = FlatStyle.Flat;
            btnHorariosClases.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnHorariosClases.ForeColor = Color.White;
            btnHorariosClases.Margin = new Padding(0);
            btnHorariosClases.Name = "btnHorariosClases";
            btnHorariosClases.Padding = new Padding(36, 0, 0, 0);
            btnHorariosClases.Size = new Size(263, 40);
            btnHorariosClases.Text = "HORARIOS DE CLASES";
            btnHorariosClases.TextAlign = ContentAlignment.MiddleLeft;
            btnHorariosClases.UseVisualStyleBackColor = false;
            btnHorariosClases.Click += btnHorariosClases_Click;
            btnCategoriasProductos.BackColor = Color.Black;
            btnCategoriasProductos.Cursor = Cursors.Hand;
            btnCategoriasProductos.FlatAppearance.BorderSize = 0;
            btnCategoriasProductos.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnCategoriasProductos.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnCategoriasProductos.FlatStyle = FlatStyle.Flat;
            btnCategoriasProductos.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnCategoriasProductos.ForeColor = Color.White;
            btnCategoriasProductos.Margin = new Padding(0);
            btnCategoriasProductos.Name = "btnCategoriasProductos";
            btnCategoriasProductos.Padding = new Padding(36, 0, 0, 0);
            btnCategoriasProductos.Size = new Size(263, 40);
            btnCategoriasProductos.Text = "CATEGORÍAS DE PRODUCTOS";
            btnCategoriasProductos.TextAlign = ContentAlignment.MiddleLeft;
            btnCategoriasProductos.UseVisualStyleBackColor = false;
            btnCategoriasProductos.Click += btnCategoriasProductos_Click;
            btnProductos.BackColor = Color.Black;
            btnProductos.Cursor = Cursors.Hand;
            btnProductos.FlatAppearance.BorderSize = 0;
            btnProductos.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnProductos.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnProductos.FlatStyle = FlatStyle.Flat;
            btnProductos.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnProductos.ForeColor = Color.White;
            btnProductos.Margin = new Padding(0);
            btnProductos.Name = "btnProductos";
            btnProductos.Padding = new Padding(36, 0, 0, 0);
            btnProductos.Size = new Size(263, 40);
            btnProductos.Text = "PRODUCTOS";
            btnProductos.TextAlign = ContentAlignment.MiddleLeft;
            btnProductos.UseVisualStyleBackColor = false;
            btnProductos.Click += btnProductos_Click;
            btnProveedores.BackColor = Color.Black;
            btnProveedores.Cursor = Cursors.Hand;
            btnProveedores.FlatAppearance.BorderSize = 0;
            btnProveedores.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnProveedores.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnProveedores.FlatStyle = FlatStyle.Flat;
            btnProveedores.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnProveedores.ForeColor = Color.White;
            btnProveedores.Margin = new Padding(0);
            btnProveedores.Name = "btnProveedores";
            btnProveedores.Padding = new Padding(36, 0, 0, 0);
            btnProveedores.Size = new Size(263, 40);
            btnProveedores.Text = "PROVEEDORES";
            btnProveedores.TextAlign = ContentAlignment.MiddleLeft;
            btnProveedores.UseVisualStyleBackColor = false;
            btnProveedores.Click += btnProveedores_Click;
            btnConsultas.BackColor = Color.Black;
            btnConsultas.Cursor = Cursors.Hand;
            btnConsultas.FlatAppearance.BorderSize = 0;
            btnConsultas.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultas.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultas.FlatStyle = FlatStyle.Flat;
            btnConsultas.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnConsultas.ForeColor = Color.White;
            btnConsultas.Margin = new Padding(0);
            btnConsultas.Name = "btnConsultas";
            btnConsultas.Padding = new Padding(21, 0, 0, 0);
            btnConsultas.Size = new Size(263, 44);
            btnConsultas.Text = ">  CONSULTAS";
            btnConsultas.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultas.UseVisualStyleBackColor = false;
            btnConsultas.Click += btnConsultas_Click;
            pnlSubmenuConsultas.BackColor = Color.Black;
            pnlSubmenuConsultas.Controls.Add(btnConsultaEntrenadores);
            pnlSubmenuConsultas.Controls.Add(btnConsultaTiposMembresias);
            pnlSubmenuConsultas.Controls.Add(btnConsultaClases);
            pnlSubmenuConsultas.Controls.Add(btnConsultaReservas);
            pnlSubmenuConsultas.Controls.Add(btnConsultaCargos);
            pnlSubmenuConsultas.Controls.Add(btnConsultaProductos);
            pnlSubmenuConsultas.Controls.Add(btnConsultaVentas);
            pnlSubmenuConsultas.Controls.Add(btnConsultaCompras);
            pnlSubmenuConsultas.Controls.Add(btnConsultaProveedores);
            pnlSubmenuConsultas.Controls.Add(btnConsultaCobros);
            pnlSubmenuConsultas.FlowDirection = FlowDirection.TopDown;
            pnlSubmenuConsultas.Margin = new Padding(0);
            pnlSubmenuConsultas.Name = "pnlSubmenuConsultas";
            pnlSubmenuConsultas.Size = new Size(263, 400);
            pnlSubmenuConsultas.Visible = false;
            pnlSubmenuConsultas.WrapContents = false;
            btnConsultaEntrenadores.BackColor = Color.Black;
            btnConsultaEntrenadores.Cursor = Cursors.Hand;
            btnConsultaEntrenadores.FlatAppearance.BorderSize = 0;
            btnConsultaEntrenadores.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaEntrenadores.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaEntrenadores.FlatStyle = FlatStyle.Flat;
            btnConsultaEntrenadores.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaEntrenadores.ForeColor = Color.White;
            btnConsultaEntrenadores.Margin = new Padding(0);
            btnConsultaEntrenadores.Name = "btnConsultaEntrenadores";
            btnConsultaEntrenadores.Padding = new Padding(36, 0, 0, 0);
            btnConsultaEntrenadores.Size = new Size(263, 40);
            btnConsultaEntrenadores.Text = "ENTRENADORES";
            btnConsultaEntrenadores.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaEntrenadores.UseVisualStyleBackColor = false;
            btnConsultaEntrenadores.Click += btnConsultaEntrenadores_Click;
            btnConsultaTiposMembresias.BackColor = Color.Black;
            btnConsultaTiposMembresias.Cursor = Cursors.Hand;
            btnConsultaTiposMembresias.FlatAppearance.BorderSize = 0;
            btnConsultaTiposMembresias.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaTiposMembresias.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaTiposMembresias.FlatStyle = FlatStyle.Flat;
            btnConsultaTiposMembresias.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaTiposMembresias.ForeColor = Color.White;
            btnConsultaTiposMembresias.Margin = new Padding(0);
            btnConsultaTiposMembresias.Name = "btnConsultaTiposMembresias";
            btnConsultaTiposMembresias.Padding = new Padding(36, 0, 0, 0);
            btnConsultaTiposMembresias.Size = new Size(263, 40);
            btnConsultaTiposMembresias.Text = "MEMBRESÍAS";
            btnConsultaTiposMembresias.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaTiposMembresias.UseVisualStyleBackColor = false;
            btnConsultaTiposMembresias.Click += btnConsultaTiposMembresias_Click;
            btnConsultaClases.BackColor = Color.Black;
            btnConsultaClases.Cursor = Cursors.Hand;
            btnConsultaClases.FlatAppearance.BorderSize = 0;
            btnConsultaClases.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaClases.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaClases.FlatStyle = FlatStyle.Flat;
            btnConsultaClases.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaClases.ForeColor = Color.White;
            btnConsultaClases.Margin = new Padding(0);
            btnConsultaClases.Name = "btnConsultaClases";
            btnConsultaClases.Padding = new Padding(36, 0, 0, 0);
            btnConsultaClases.Size = new Size(263, 40);
            btnConsultaClases.Text = "CLASES";
            btnConsultaClases.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaClases.UseVisualStyleBackColor = false;
            btnConsultaClases.Click += btnConsultaClases_Click;
            btnConsultaReservas.BackColor = Color.Black;
            btnConsultaReservas.Cursor = Cursors.Hand;
            btnConsultaReservas.FlatAppearance.BorderSize = 0;
            btnConsultaReservas.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaReservas.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaReservas.FlatStyle = FlatStyle.Flat;
            btnConsultaReservas.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaReservas.ForeColor = Color.White;
            btnConsultaReservas.Margin = new Padding(0);
            btnConsultaReservas.Name = "btnConsultaReservas";
            btnConsultaReservas.Padding = new Padding(36, 0, 0, 0);
            btnConsultaReservas.Size = new Size(263, 40);
            btnConsultaReservas.Text = "RESERVAS";
            btnConsultaReservas.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaReservas.UseVisualStyleBackColor = false;
            btnConsultaReservas.Click += btnConsultaReservas_Click;
            btnConsultaCargos.BackColor = Color.Black;
            btnConsultaCargos.Cursor = Cursors.Hand;
            btnConsultaCargos.FlatAppearance.BorderSize = 0;
            btnConsultaCargos.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaCargos.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaCargos.FlatStyle = FlatStyle.Flat;
            btnConsultaCargos.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaCargos.ForeColor = Color.White;
            btnConsultaCargos.Margin = new Padding(0);
            btnConsultaCargos.Name = "btnConsultaCargos";
            btnConsultaCargos.Padding = new Padding(36, 0, 0, 0);
            btnConsultaCargos.Size = new Size(263, 40);
            btnConsultaCargos.Text = "CARGOS";
            btnConsultaCargos.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaCargos.UseVisualStyleBackColor = false;
            btnConsultaCargos.Click += btnConsultaCargos_Click;
            btnConsultaProductos.BackColor = Color.Black;
            btnConsultaProductos.Cursor = Cursors.Hand;
            btnConsultaProductos.FlatAppearance.BorderSize = 0;
            btnConsultaProductos.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaProductos.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaProductos.FlatStyle = FlatStyle.Flat;
            btnConsultaProductos.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaProductos.ForeColor = Color.White;
            btnConsultaProductos.Margin = new Padding(0);
            btnConsultaProductos.Name = "btnConsultaProductos";
            btnConsultaProductos.Padding = new Padding(36, 0, 0, 0);
            btnConsultaProductos.Size = new Size(263, 40);
            btnConsultaProductos.Text = "PRODUCTOS";
            btnConsultaProductos.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaProductos.UseVisualStyleBackColor = false;
            btnConsultaProductos.Click += btnConsultaProductos_Click;
            btnConsultaVentas.BackColor = Color.Black;
            btnConsultaVentas.Cursor = Cursors.Hand;
            btnConsultaVentas.FlatAppearance.BorderSize = 0;
            btnConsultaVentas.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaVentas.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaVentas.FlatStyle = FlatStyle.Flat;
            btnConsultaVentas.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaVentas.ForeColor = Color.White;
            btnConsultaVentas.Margin = new Padding(0);
            btnConsultaVentas.Name = "btnConsultaVentas";
            btnConsultaVentas.Padding = new Padding(36, 0, 0, 0);
            btnConsultaVentas.Size = new Size(263, 40);
            btnConsultaVentas.Text = "VENTAS";
            btnConsultaVentas.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaVentas.UseVisualStyleBackColor = false;
            btnConsultaVentas.Click += btnConsultaVentas_Click;
            btnConsultaCompras.BackColor = Color.Black;
            btnConsultaCompras.Cursor = Cursors.Hand;
            btnConsultaCompras.FlatAppearance.BorderSize = 0;
            btnConsultaCompras.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaCompras.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaCompras.FlatStyle = FlatStyle.Flat;
            btnConsultaCompras.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaCompras.ForeColor = Color.White;
            btnConsultaCompras.Margin = new Padding(0);
            btnConsultaCompras.Name = "btnConsultaCompras";
            btnConsultaCompras.Padding = new Padding(36, 0, 0, 0);
            btnConsultaCompras.Size = new Size(263, 40);
            btnConsultaCompras.Text = "COMPRAS";
            btnConsultaCompras.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaCompras.UseVisualStyleBackColor = false;
            btnConsultaCompras.Click += btnConsultaCompras_Click;
            btnConsultaProveedores.BackColor = Color.Black;
            btnConsultaProveedores.Cursor = Cursors.Hand;
            btnConsultaProveedores.FlatAppearance.BorderSize = 0;
            btnConsultaProveedores.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaProveedores.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaProveedores.FlatStyle = FlatStyle.Flat;
            btnConsultaProveedores.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaProveedores.ForeColor = Color.White;
            btnConsultaProveedores.Margin = new Padding(0);
            btnConsultaProveedores.Name = "btnConsultaProveedores";
            btnConsultaProveedores.Padding = new Padding(36, 0, 0, 0);
            btnConsultaProveedores.Size = new Size(263, 40);
            btnConsultaProveedores.Text = "PROVEEDORES";
            btnConsultaProveedores.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaProveedores.UseVisualStyleBackColor = false;
            btnConsultaProveedores.Click += btnConsultaProveedores_Click;
            btnConsultaCobros.BackColor = Color.Black;
            btnConsultaCobros.Cursor = Cursors.Hand;
            btnConsultaCobros.FlatAppearance.BorderSize = 0;
            btnConsultaCobros.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnConsultaCobros.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnConsultaCobros.FlatStyle = FlatStyle.Flat;
            btnConsultaCobros.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            btnConsultaCobros.ForeColor = Color.White;
            btnConsultaCobros.Margin = new Padding(0);
            btnConsultaCobros.Name = "btnConsultaCobros";
            btnConsultaCobros.Padding = new Padding(36, 0, 0, 0);
            btnConsultaCobros.Size = new Size(263, 40);
            btnConsultaCobros.Text = "COBROS";
            btnConsultaCobros.TextAlign = ContentAlignment.MiddleLeft;
            btnConsultaCobros.UseVisualStyleBackColor = false;
            btnConsultaCobros.Click += btnConsultaCobros_Click;
            pnlSesion.BackColor = Color.Black;
            pnlSesion.Controls.Add(tlpBotonesSesion);
            pnlSesion.Controls.Add(lblRol);
            pnlSesion.Controls.Add(lblBienvenida);
            pnlSesion.Dock = DockStyle.Bottom;
            pnlSesion.Location = new Point(0, 587);
            pnlSesion.Name = "pnlSesion";
            pnlSesion.Size = new Size(263, 133);
            pnlSesion.TabIndex = 2;
            tlpBotonesSesion.ColumnCount = 2;
            tlpBotonesSesion.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tlpBotonesSesion.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tlpBotonesSesion.Controls.Add(btnCerrarSesion, 0, 0);
            tlpBotonesSesion.Controls.Add(btnSalir, 1, 0);
            tlpBotonesSesion.Dock = DockStyle.Bottom;
            tlpBotonesSesion.Location = new Point(0, 77);
            tlpBotonesSesion.Name = "tlpBotonesSesion";
            tlpBotonesSesion.Padding = new Padding(7, 0, 7, 0);
            tlpBotonesSesion.RowCount = 1;
            tlpBotonesSesion.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tlpBotonesSesion.Size = new Size(263, 56);
            tlpBotonesSesion.TabIndex = 4;
            btnCerrarSesion.BackColor = Color.FromArgb(124, 142, 163);
            btnCerrarSesion.Cursor = Cursors.Hand;
            btnCerrarSesion.Dock = DockStyle.Fill;
            btnCerrarSesion.FlatAppearance.BorderSize = 0;
            btnCerrarSesion.FlatStyle = FlatStyle.Flat;
            btnCerrarSesion.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnCerrarSesion.ForeColor = Color.White;
            btnCerrarSesion.Margin = new Padding(5);
            btnCerrarSesion.Name = "btnCerrarSesion";
            btnCerrarSesion.Text = "CERRAR SESIÓN";
            btnCerrarSesion.UseVisualStyleBackColor = false;
            btnCerrarSesion.Click += btnCerrarSesion_Click;
            btnSalir.BackColor = Color.White;
            btnSalir.Cursor = Cursors.Hand;
            btnSalir.Dock = DockStyle.Fill;
            btnSalir.FlatAppearance.BorderColor = Color.White;
            btnSalir.FlatStyle = FlatStyle.Flat;
            btnSalir.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnSalir.ForeColor = Color.Black;
            btnSalir.Margin = new Padding(5);
            btnSalir.Name = "btnSalir";
            btnSalir.Text = "SALIR";
            btnSalir.UseVisualStyleBackColor = false;
            btnSalir.Click += btnSalir_Click;
            lblRol.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            lblRol.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblRol.ForeColor = Color.FromArgb(124, 142, 163);
            lblRol.Location = new Point(15, 43);
            lblRol.Name = "lblRol";
            lblRol.Size = new Size(233, 29);
            lblBienvenida.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            lblBienvenida.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblBienvenida.ForeColor = Color.White;
            lblBienvenida.Location = new Point(15, 5);
            lblBienvenida.Name = "lblBienvenida";
            lblBienvenida.Size = new Size(233, 36);
            lblNombreSistema.Dock = DockStyle.Top;
            lblNombreSistema.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblNombreSistema.ForeColor = Color.White;
            lblNombreSistema.Location = new Point(0, 0);
            lblNombreSistema.Name = "lblNombreSistema";
            lblNombreSistema.Size = new Size(263, 96);
            lblNombreSistema.Text = "Super Saija Gym";
            lblNombreSistema.TextAlign = ContentAlignment.MiddleCenter;
            pnlContenido.BackColor = Color.Black;
            pnlContenido.Controls.Add(picInicio);
            pnlContenido.Dock = DockStyle.Fill;
            pnlContenido.Location = new Point(263, 0);
            pnlContenido.Name = "pnlContenido";
            pnlContenido.Padding = new Padding(12);
            pnlContenido.Size = new Size(788, 720);
            pnlContenido.TabIndex = 2;
            picInicio.BackColor = Color.Black;
            picInicio.Dock = DockStyle.Fill;
            picInicio.Location = new Point(12, 12);
            picInicio.Name = "picInicio";
            picInicio.Size = new Size(764, 696);
            picInicio.SizeMode = PictureBoxSizeMode.Zoom;
            picInicio.TabIndex = 0;
            picInicio.TabStop = false;
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(1051, 720);
            Controls.Add(pnlContenido);
            Controls.Add(pnlMenuLateral);
            Font = new Font("Segoe UI", 9F);
            MinimumSize = new Size(1049, 704);
            Name = "FrmPrincipal";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Super Saija Gym";
            Load += FrmPrincipal_Load;
            pnlMenuLateral.ResumeLayout(false);
            pnlOpciones.ResumeLayout(false);
            pnlSubmenuMantenimientos.ResumeLayout(false);
            pnlSubmenuConsultas.ResumeLayout(false);
            pnlSesion.ResumeLayout(false);
            tlpBotonesSesion.ResumeLayout(false);
            pnlContenido.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picInicio).EndInit();
            ResumeLayout(false);
        }
    }
}
