namespace Proyecto_Gym_ProgramacionIII_Jeovanny.Formularios
{
    partial class FrmProductoDetalle
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pnlImagen;
        private Label lblTitulo;
        private Label lblCodigo;
        private Label lblNombre;
        private Label lblDescripcion;
        private Label lblCategoria;
        private Label lblPrecioCompra;
        private Label lblPrecioVenta;
        private Label lblStock;
        private Label lblStockMinimo;
        private Label lblImagen;
        private TextBox txtCodigo;
        private TextBox txtNombre;
        private TextBox txtDescripcion;
        private ComboBox cmbCategoria;
        private NumericUpDown nudPrecioCompra;
        private NumericUpDown nudPrecioVenta;
        private NumericUpDown nudStock;
        private NumericUpDown nudStockMinimo;
        private PictureBox picImagen;
        private Button btnSeleccionarImagen;
        private Button btnQuitarImagen;
        private CheckBox chkEstado;
        private Label lblMensaje;
        private Button btnGuardar;
        private Button btnCancelar;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            pnlImagen = new Panel();
            lblTitulo = new Label();
            lblCodigo = new Label();
            lblNombre = new Label();
            lblDescripcion = new Label();
            lblCategoria = new Label();
            lblPrecioCompra = new Label();
            lblPrecioVenta = new Label();
            lblStock = new Label();
            lblStockMinimo = new Label();
            lblImagen = new Label();
            txtCodigo = new TextBox();
            txtNombre = new TextBox();
            txtDescripcion = new TextBox();
            cmbCategoria = new ComboBox();
            nudPrecioCompra = new NumericUpDown();
            nudPrecioVenta = new NumericUpDown();
            nudStock = new NumericUpDown();
            nudStockMinimo = new NumericUpDown();
            picImagen = new PictureBox();
            btnSeleccionarImagen = new Button();
            btnQuitarImagen = new Button();
            chkEstado = new CheckBox();
            lblMensaje = new Label();
            btnGuardar = new Button();
            btnCancelar = new Button();
            ((System.ComponentModel.ISupportInitialize)nudPrecioCompra).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudPrecioVenta).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudStock).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudStockMinimo).BeginInit();
            ((System.ComponentModel.ISupportInitialize)picImagen).BeginInit();
            pnlImagen.SuspendLayout();
            SuspendLayout();
            pnlImagen.BackColor = Color.Black;
            pnlImagen.Controls.Add(lblImagen);
            pnlImagen.Controls.Add(picImagen);
            pnlImagen.Controls.Add(btnSeleccionarImagen);
            pnlImagen.Controls.Add(btnQuitarImagen);
            pnlImagen.Controls.Add(chkEstado);
            pnlImagen.Dock = DockStyle.Left;
            pnlImagen.Location = new Point(0, 0);
            pnlImagen.Name = "pnlImagen";
            pnlImagen.Size = new Size(320, 610);
            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Segoe UI", 24F, FontStyle.Bold);
            lblTitulo.Location = new Point(370, 35);
            lblTitulo.Text = "Nuevo producto";
            lblCodigo.AutoSize = true;
            lblCodigo.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblCodigo.Location = new Point(370, 105);
            lblCodigo.Text = "Código";
            lblNombre.AutoSize = true;
            lblNombre.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblNombre.Location = new Point(645, 105);
            lblNombre.Text = "Nombre";
            lblDescripcion.AutoSize = true;
            lblDescripcion.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblDescripcion.Location = new Point(370, 170);
            lblDescripcion.Text = "Descripción";
            lblCategoria.AutoSize = true;
            lblCategoria.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblCategoria.Location = new Point(370, 265);
            lblCategoria.Text = "Categoría";
            lblPrecioCompra.AutoSize = true;
            lblPrecioCompra.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblPrecioCompra.Location = new Point(370, 325);
            lblPrecioCompra.Text = "Precio de compra";
            lblPrecioVenta.AutoSize = true;
            lblPrecioVenta.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblPrecioVenta.Location = new Point(645, 325);
            lblPrecioVenta.Text = "Precio de venta";
            lblStock.AutoSize = true;
            lblStock.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblStock.Location = new Point(370, 385);
            lblStock.Text = "Existencia";
            lblStockMinimo.AutoSize = true;
            lblStockMinimo.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblStockMinimo.Location = new Point(645, 385);
            lblStockMinimo.Text = "Existencia mínima";
            lblImagen.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblImagen.ForeColor = Color.White;
            lblImagen.Location = new Point(35, 30);
            lblImagen.Name = "lblImagen";
            lblImagen.Size = new Size(250, 40);
            lblImagen.Text = "IMAGEN DEL PRODUCTO";
            lblImagen.TextAlign = ContentAlignment.MiddleCenter;
            txtCodigo.Font = new Font("Segoe UI", 10F);
            txtCodigo.Location = new Point(370, 127);
            txtCodigo.Name = "txtCodigo";
            txtCodigo.Size = new Size(250, 25);
            txtCodigo.MaxLength = 30;
            txtNombre.Font = new Font("Segoe UI", 10F);
            txtNombre.Location = new Point(645, 127);
            txtNombre.Name = "txtNombre";
            txtNombre.Size = new Size(250, 25);
            txtNombre.MaxLength = 100;
            txtDescripcion.Font = new Font("Segoe UI", 10F);
            txtDescripcion.Location = new Point(370, 192);
            txtDescripcion.MaxLength = 250;
            txtDescripcion.Multiline = true;
            txtDescripcion.Name = "txtDescripcion";
            txtDescripcion.Size = new Size(525, 58);
            cmbCategoria.Font = new Font("Segoe UI", 10F);
            cmbCategoria.Location = new Point(370, 287);
            cmbCategoria.Name = "cmbCategoria";
            cmbCategoria.Size = new Size(525, 25);
            cmbCategoria.DropDownStyle = ComboBoxStyle.DropDownList;
            nudPrecioCompra.Font = new Font("Segoe UI", 10F);
            nudPrecioCompra.Location = new Point(370, 347);
            nudPrecioCompra.Name = "nudPrecioCompra";
            nudPrecioCompra.Size = new Size(250, 25);
            nudPrecioCompra.DecimalPlaces = 2;
            nudPrecioCompra.Maximum = 9999999999.99M;
            nudPrecioCompra.ThousandsSeparator = true;
            nudPrecioVenta.Font = new Font("Segoe UI", 10F);
            nudPrecioVenta.Location = new Point(645, 347);
            nudPrecioVenta.Name = "nudPrecioVenta";
            nudPrecioVenta.Size = new Size(250, 25);
            nudPrecioVenta.DecimalPlaces = 2;
            nudPrecioVenta.Maximum = 9999999999.99M;
            nudPrecioVenta.ThousandsSeparator = true;
            nudStock.Font = new Font("Segoe UI", 10F);
            nudStock.Location = new Point(370, 407);
            nudStock.Name = "nudStock";
            nudStock.Size = new Size(250, 25);
            nudStock.Maximum = int.MaxValue;
            nudStockMinimo.Font = new Font("Segoe UI", 10F);
            nudStockMinimo.Location = new Point(645, 407);
            nudStockMinimo.Name = "nudStockMinimo";
            nudStockMinimo.Size = new Size(250, 25);
            nudStockMinimo.Maximum = int.MaxValue;
            picImagen.BackColor = Color.Black;
            picImagen.Location = new Point(35, 95);
            picImagen.Name = "picImagen";
            picImagen.Size = new Size(250, 300);
            picImagen.SizeMode = PictureBoxSizeMode.Zoom;
            picImagen.TabStop = false;
            btnSeleccionarImagen.BackColor = Color.FromArgb(124, 142, 163);
            btnSeleccionarImagen.FlatAppearance.BorderSize = 0;
            btnSeleccionarImagen.FlatStyle = FlatStyle.Flat;
            btnSeleccionarImagen.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnSeleccionarImagen.ForeColor = Color.White;
            btnSeleccionarImagen.Location = new Point(35, 420);
            btnSeleccionarImagen.Size = new Size(120, 44);
            btnSeleccionarImagen.Text = "SELECCIONAR IMAGEN";
            btnSeleccionarImagen.UseVisualStyleBackColor = false;
            btnSeleccionarImagen.Cursor = Cursors.Hand;
            btnSeleccionarImagen.Name = "btnSeleccionarImagen";
            btnSeleccionarImagen.Click += btnSeleccionarImagen_Click;
            btnQuitarImagen.BackColor = Color.White;
            btnQuitarImagen.FlatAppearance.BorderSize = 0;
            btnQuitarImagen.FlatStyle = FlatStyle.Flat;
            btnQuitarImagen.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnQuitarImagen.ForeColor = Color.Black;
            btnQuitarImagen.Location = new Point(165, 420);
            btnQuitarImagen.Size = new Size(120, 44);
            btnQuitarImagen.Text = "QUITAR IMAGEN";
            btnQuitarImagen.UseVisualStyleBackColor = false;
            btnQuitarImagen.Cursor = Cursors.Hand;
            btnQuitarImagen.Name = "btnQuitarImagen";
            btnQuitarImagen.Click += btnQuitarImagen_Click;
            chkEstado.AutoSize = true;
            chkEstado.BackColor = Color.Black;
            chkEstado.Checked = true;
            chkEstado.CheckState = CheckState.Checked;
            chkEstado.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            chkEstado.ForeColor = Color.White;
            chkEstado.Location = new Point(35, 545);
            chkEstado.Name = "chkEstado";
            chkEstado.Text = "Producto activo";
            chkEstado.UseVisualStyleBackColor = false;
            lblMensaje.ForeColor = Color.Firebrick;
            lblMensaje.Location = new Point(370, 465);
            lblMensaje.Name = "lblMensaje";
            lblMensaje.Size = new Size(250, 75);
            btnGuardar.BackColor = Color.FromArgb(124, 142, 163);
            btnGuardar.FlatAppearance.BorderSize = 0;
            btnGuardar.FlatStyle = FlatStyle.Flat;
            btnGuardar.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnGuardar.ForeColor = Color.White;
            btnGuardar.Location = new Point(645, 535);
            btnGuardar.Size = new Size(120, 40);
            btnGuardar.Text = "GUARDAR";
            btnGuardar.UseVisualStyleBackColor = false;
            btnGuardar.Name = "btnGuardar";
            btnGuardar.Click += btnGuardar_Click;
            btnCancelar.BackColor = Color.WhiteSmoke;
            btnCancelar.FlatAppearance.BorderSize = 0;
            btnCancelar.FlatStyle = FlatStyle.Flat;
            btnCancelar.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnCancelar.ForeColor = Color.Black;
            btnCancelar.Location = new Point(775, 535);
            btnCancelar.Size = new Size(120, 40);
            btnCancelar.Text = "CANCELAR";
            btnCancelar.UseVisualStyleBackColor = false;
            btnCancelar.DialogResult = DialogResult.Cancel;
            btnCancelar.Name = "btnCancelar";
            AcceptButton = btnGuardar;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            CancelButton = btnCancelar;
            ClientSize = new Size(920, 610);
            Controls.Add(pnlImagen);
            Controls.Add(lblTitulo);
            Controls.Add(lblCodigo);
            Controls.Add(lblNombre);
            Controls.Add(lblDescripcion);
            Controls.Add(lblCategoria);
            Controls.Add(lblPrecioCompra);
            Controls.Add(lblPrecioVenta);
            Controls.Add(lblStock);
            Controls.Add(lblStockMinimo);
            Controls.Add(txtCodigo);
            Controls.Add(txtNombre);
            Controls.Add(txtDescripcion);
            Controls.Add(cmbCategoria);
            Controls.Add(nudPrecioCompra);
            Controls.Add(nudPrecioVenta);
            Controls.Add(nudStock);
            Controls.Add(nudStockMinimo);
            Controls.Add(lblMensaje);
            Controls.Add(btnGuardar);
            Controls.Add(btnCancelar);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "FrmProductoDetalle";
            StartPosition = FormStartPosition.CenterParent;
            Text = "Nuevo producto";
            FormClosed += FrmProductoDetalle_FormClosed;
            Load += FrmProductoDetalle_Load;
            ((System.ComponentModel.ISupportInitialize)nudPrecioCompra).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudPrecioVenta).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudStock).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudStockMinimo).EndInit();
            ((System.ComponentModel.ISupportInitialize)picImagen).EndInit();
            pnlImagen.ResumeLayout(false);
            pnlImagen.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }
    }
}
