namespace Proyecto_Gym_ProgramacionIII_Jeovanny.Formularios
{
    partial class FrmPrincipal
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            pnlMenuLateral = new Panel();
            pnlOpciones = new Panel();
            btnProveedores = new Button();
            btnProductos = new Button();
            btnCategoriasProductos = new Button();
            btnHorariosClases = new Button();
            btnClasesActividades = new Button();
            btnTiposMembresias = new Button();
            btnEntrenadores = new Button();
            btnClientes = new Button();
            btnInicio = new Button();
            pnlSesion = new Panel();
            tlpBotonesSesion = new TableLayoutPanel();
            btnSalir = new Button();
            btnCerrarSesion = new Button();
            lblRol = new Label();
            lblBienvenida = new Label();
            lblNombreSistema = new Label();
            pnlEncabezado = new Panel();
            lblTituloSeccion = new Label();
            pnlContenido = new Panel();
            pnlMenuLateral.SuspendLayout();
            pnlOpciones.SuspendLayout();
            pnlSesion.SuspendLayout();
            tlpBotonesSesion.SuspendLayout();
            pnlEncabezado.SuspendLayout();
            SuspendLayout();
            pnlMenuLateral.BackColor = Color.Black;
            pnlMenuLateral.Controls.Add(pnlOpciones);
            pnlMenuLateral.Controls.Add(pnlSesion);
            pnlMenuLateral.Controls.Add(lblNombreSistema);
            pnlMenuLateral.Dock = DockStyle.Left;
            pnlMenuLateral.Location = new Point(0, 0);
            pnlMenuLateral.Name = "pnlMenuLateral";
            pnlMenuLateral.Size = new Size(230, 540);
            pnlMenuLateral.TabIndex = 0;
            pnlOpciones.AutoScroll = false;
            pnlOpciones.BackColor = Color.Black;
            pnlOpciones.Controls.Add(btnProveedores);
            pnlOpciones.Controls.Add(btnProductos);
            pnlOpciones.Controls.Add(btnCategoriasProductos);
            pnlOpciones.Controls.Add(btnHorariosClases);
            pnlOpciones.Controls.Add(btnClasesActividades);
            pnlOpciones.Controls.Add(btnTiposMembresias);
            pnlOpciones.Controls.Add(btnEntrenadores);
            pnlOpciones.Controls.Add(btnClientes);
            pnlOpciones.Controls.Add(btnInicio);
            pnlOpciones.Dock = DockStyle.Fill;
            pnlOpciones.Location = new Point(0, 72);
            pnlOpciones.Name = "pnlOpciones";
            pnlOpciones.Size = new Size(230, 368);
            pnlOpciones.TabIndex = 1;
            btnProveedores.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            btnProveedores.BackColor = Color.Black;
            btnProveedores.Cursor = Cursors.Hand;
            btnProveedores.FlatAppearance.BorderSize = 0;
            btnProveedores.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnProveedores.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnProveedores.FlatStyle = FlatStyle.Flat;
            btnProveedores.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnProveedores.ForeColor = Color.White;
            btnProveedores.Location = new Point(0, 324);
            btnProveedores.Name = "btnProveedores";
            btnProveedores.Padding = new Padding(18, 0, 0, 0);
            btnProveedores.Size = new Size(230, 40);
            btnProveedores.TabIndex = 8;
            btnProveedores.Text = "PROVEEDORES";
            btnProveedores.TextAlign = ContentAlignment.MiddleLeft;
            btnProveedores.UseVisualStyleBackColor = false;
            btnProveedores.Click += btnProveedores_Click;
            btnProductos.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            btnProductos.BackColor = Color.Black;
            btnProductos.Cursor = Cursors.Hand;
            btnProductos.FlatAppearance.BorderSize = 0;
            btnProductos.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnProductos.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnProductos.FlatStyle = FlatStyle.Flat;
            btnProductos.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnProductos.ForeColor = Color.White;
            btnProductos.Location = new Point(0, 284);
            btnProductos.Name = "btnProductos";
            btnProductos.Padding = new Padding(18, 0, 0, 0);
            btnProductos.Size = new Size(230, 40);
            btnProductos.TabIndex = 7;
            btnProductos.Text = "PRODUCTOS";
            btnProductos.TextAlign = ContentAlignment.MiddleLeft;
            btnProductos.UseVisualStyleBackColor = false;
            btnProductos.Click += btnProductos_Click;
            btnCategoriasProductos.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            btnCategoriasProductos.BackColor = Color.Black;
            btnCategoriasProductos.Cursor = Cursors.Hand;
            btnCategoriasProductos.FlatAppearance.BorderSize = 0;
            btnCategoriasProductos.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnCategoriasProductos.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnCategoriasProductos.FlatStyle = FlatStyle.Flat;
            btnCategoriasProductos.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnCategoriasProductos.ForeColor = Color.White;
            btnCategoriasProductos.Location = new Point(0, 244);
            btnCategoriasProductos.Name = "btnCategoriasProductos";
            btnCategoriasProductos.Padding = new Padding(18, 0, 0, 0);
            btnCategoriasProductos.Size = new Size(230, 40);
            btnCategoriasProductos.TabIndex = 6;
            btnCategoriasProductos.Text = "CATEGORÍAS DE PRODUCTOS";
            btnCategoriasProductos.TextAlign = ContentAlignment.MiddleLeft;
            btnCategoriasProductos.UseVisualStyleBackColor = false;
            btnCategoriasProductos.Click += btnCategoriasProductos_Click;
            btnHorariosClases.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            btnHorariosClases.BackColor = Color.Black;
            btnHorariosClases.Cursor = Cursors.Hand;
            btnHorariosClases.FlatAppearance.BorderSize = 0;
            btnHorariosClases.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnHorariosClases.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnHorariosClases.FlatStyle = FlatStyle.Flat;
            btnHorariosClases.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnHorariosClases.ForeColor = Color.White;
            btnHorariosClases.Location = new Point(0, 204);
            btnHorariosClases.Name = "btnHorariosClases";
            btnHorariosClases.Padding = new Padding(18, 0, 0, 0);
            btnHorariosClases.Size = new Size(230, 40);
            btnHorariosClases.TabIndex = 5;
            btnHorariosClases.Text = "HORARIOS DE CLASES";
            btnHorariosClases.TextAlign = ContentAlignment.MiddleLeft;
            btnHorariosClases.UseVisualStyleBackColor = false;
            btnHorariosClases.Click += btnHorariosClases_Click;
            btnClasesActividades.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            btnClasesActividades.BackColor = Color.Black;
            btnClasesActividades.Cursor = Cursors.Hand;
            btnClasesActividades.FlatAppearance.BorderSize = 0;
            btnClasesActividades.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnClasesActividades.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnClasesActividades.FlatStyle = FlatStyle.Flat;
            btnClasesActividades.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnClasesActividades.ForeColor = Color.White;
            btnClasesActividades.Location = new Point(0, 164);
            btnClasesActividades.Name = "btnClasesActividades";
            btnClasesActividades.Padding = new Padding(18, 0, 0, 0);
            btnClasesActividades.Size = new Size(230, 40);
            btnClasesActividades.TabIndex = 4;
            btnClasesActividades.Text = "CLASES Y ACTIVIDADES";
            btnClasesActividades.TextAlign = ContentAlignment.MiddleLeft;
            btnClasesActividades.UseVisualStyleBackColor = false;
            btnClasesActividades.Click += btnClasesActividades_Click;
            btnTiposMembresias.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            btnTiposMembresias.BackColor = Color.Black;
            btnTiposMembresias.Cursor = Cursors.Hand;
            btnTiposMembresias.FlatAppearance.BorderSize = 0;
            btnTiposMembresias.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnTiposMembresias.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnTiposMembresias.FlatStyle = FlatStyle.Flat;
            btnTiposMembresias.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnTiposMembresias.ForeColor = Color.White;
            btnTiposMembresias.Location = new Point(0, 124);
            btnTiposMembresias.Name = "btnTiposMembresias";
            btnTiposMembresias.Padding = new Padding(18, 0, 0, 0);
            btnTiposMembresias.Size = new Size(230, 40);
            btnTiposMembresias.TabIndex = 3;
            btnTiposMembresias.Text = "TIPOS DE MEMBRESÍAS";
            btnTiposMembresias.TextAlign = ContentAlignment.MiddleLeft;
            btnTiposMembresias.UseVisualStyleBackColor = false;
            btnTiposMembresias.Click += btnTiposMembresias_Click;
            btnEntrenadores.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            btnEntrenadores.BackColor = Color.Black;
            btnEntrenadores.Cursor = Cursors.Hand;
            btnEntrenadores.FlatAppearance.BorderSize = 0;
            btnEntrenadores.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnEntrenadores.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnEntrenadores.FlatStyle = FlatStyle.Flat;
            btnEntrenadores.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnEntrenadores.ForeColor = Color.White;
            btnEntrenadores.Location = new Point(0, 84);
            btnEntrenadores.Name = "btnEntrenadores";
            btnEntrenadores.Padding = new Padding(18, 0, 0, 0);
            btnEntrenadores.Size = new Size(230, 40);
            btnEntrenadores.TabIndex = 2;
            btnEntrenadores.Text = "ENTRENADORES";
            btnEntrenadores.TextAlign = ContentAlignment.MiddleLeft;
            btnEntrenadores.UseVisualStyleBackColor = false;
            btnEntrenadores.Click += btnEntrenadores_Click;
            btnClientes.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            btnClientes.BackColor = Color.Black;
            btnClientes.Cursor = Cursors.Hand;
            btnClientes.FlatAppearance.BorderSize = 0;
            btnClientes.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnClientes.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnClientes.FlatStyle = FlatStyle.Flat;
            btnClientes.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnClientes.ForeColor = Color.White;
            btnClientes.Location = new Point(0, 44);
            btnClientes.Name = "btnClientes";
            btnClientes.Padding = new Padding(18, 0, 0, 0);
            btnClientes.Size = new Size(230, 40);
            btnClientes.TabIndex = 1;
            btnClientes.Text = "CLIENTES";
            btnClientes.TextAlign = ContentAlignment.MiddleLeft;
            btnClientes.UseVisualStyleBackColor = false;
            btnClientes.Click += btnClientes_Click;
            btnInicio.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            btnInicio.BackColor = Color.Black;
            btnInicio.Cursor = Cursors.Hand;
            btnInicio.FlatAppearance.BorderSize = 0;
            btnInicio.FlatAppearance.MouseDownBackColor = Color.FromArgb(100, 117, 136);
            btnInicio.FlatAppearance.MouseOverBackColor = Color.FromArgb(124, 142, 163);
            btnInicio.FlatStyle = FlatStyle.Flat;
            btnInicio.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnInicio.ForeColor = Color.White;
            btnInicio.Location = new Point(0, 4);
            btnInicio.Name = "btnInicio";
            btnInicio.Padding = new Padding(18, 0, 0, 0);
            btnInicio.Size = new Size(230, 40);
            btnInicio.TabIndex = 0;
            btnInicio.Text = "INICIO";
            btnInicio.TextAlign = ContentAlignment.MiddleLeft;
            btnInicio.UseVisualStyleBackColor = false;
            btnInicio.Click += btnInicio_Click;
            pnlSesion.BackColor = Color.Black;
            pnlSesion.Controls.Add(tlpBotonesSesion);
            pnlSesion.Controls.Add(lblRol);
            pnlSesion.Controls.Add(lblBienvenida);
            pnlSesion.Dock = DockStyle.Bottom;
            pnlSesion.Location = new Point(0, 440);
            pnlSesion.Name = "pnlSesion";
            pnlSesion.Size = new Size(230, 100);
            pnlSesion.TabIndex = 2;
            tlpBotonesSesion.ColumnCount = 2;
            tlpBotonesSesion.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tlpBotonesSesion.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tlpBotonesSesion.Controls.Add(btnCerrarSesion, 0, 0);
            tlpBotonesSesion.Controls.Add(btnSalir, 1, 0);
            tlpBotonesSesion.Dock = DockStyle.Bottom;
            tlpBotonesSesion.Location = new Point(0, 58);
            tlpBotonesSesion.Name = "tlpBotonesSesion";
            tlpBotonesSesion.Padding = new Padding(6, 0, 6, 0);
            tlpBotonesSesion.RowCount = 1;
            tlpBotonesSesion.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tlpBotonesSesion.Size = new Size(230, 42);
            tlpBotonesSesion.TabIndex = 4;
            btnSalir.BackColor = Color.White;
            btnSalir.Cursor = Cursors.Hand;
            btnSalir.Dock = DockStyle.Fill;
            btnSalir.FlatAppearance.BorderColor = Color.White;
            btnSalir.FlatStyle = FlatStyle.Flat;
            btnSalir.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnSalir.ForeColor = Color.Black;
            btnSalir.Location = new Point(119, 4);
            btnSalir.Margin = new Padding(4);
            btnSalir.Name = "btnSalir";
            btnSalir.Size = new Size(101, 34);
            btnSalir.TabIndex = 1;
            btnSalir.Text = "SALIR";
            btnSalir.UseVisualStyleBackColor = false;
            btnSalir.Click += btnSalir_Click;
            btnCerrarSesion.BackColor = Color.FromArgb(124, 142, 163);
            btnCerrarSesion.Cursor = Cursors.Hand;
            btnCerrarSesion.Dock = DockStyle.Fill;
            btnCerrarSesion.FlatAppearance.BorderSize = 0;
            btnCerrarSesion.FlatStyle = FlatStyle.Flat;
            btnCerrarSesion.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnCerrarSesion.ForeColor = Color.White;
            btnCerrarSesion.Location = new Point(10, 4);
            btnCerrarSesion.Margin = new Padding(4);
            btnCerrarSesion.Name = "btnCerrarSesion";
            btnCerrarSesion.Size = new Size(101, 34);
            btnCerrarSesion.TabIndex = 0;
            btnCerrarSesion.Text = "CERRAR SESIÓN";
            btnCerrarSesion.UseVisualStyleBackColor = false;
            btnCerrarSesion.Click += btnCerrarSesion_Click;
            lblRol.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            lblRol.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblRol.ForeColor = Color.FromArgb(124, 142, 163);
            lblRol.Location = new Point(13, 32);
            lblRol.Name = "lblRol";
            lblRol.Size = new Size(204, 22);
            lblRol.TabIndex = 3;
            lblBienvenida.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            lblBienvenida.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblBienvenida.ForeColor = Color.White;
            lblBienvenida.Location = new Point(13, 4);
            lblBienvenida.Name = "lblBienvenida";
            lblBienvenida.Size = new Size(204, 27);
            lblBienvenida.TabIndex = 2;
            lblNombreSistema.Dock = DockStyle.Top;
            lblNombreSistema.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblNombreSistema.ForeColor = Color.White;
            lblNombreSistema.Location = new Point(0, 0);
            lblNombreSistema.Name = "lblNombreSistema";
            lblNombreSistema.Size = new Size(230, 72);
            lblNombreSistema.TabIndex = 0;
            lblNombreSistema.Text = "Super Saija Gym";
            lblNombreSistema.TextAlign = ContentAlignment.MiddleCenter;
            pnlEncabezado.BackColor = Color.White;
            pnlEncabezado.Controls.Add(lblTituloSeccion);
            pnlEncabezado.Dock = DockStyle.Top;
            pnlEncabezado.Location = new Point(230, 0);
            pnlEncabezado.Name = "pnlEncabezado";
            pnlEncabezado.Size = new Size(690, 65);
            pnlEncabezado.TabIndex = 1;
            lblTituloSeccion.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            lblTituloSeccion.Font = new Font("Segoe UI", 20F, FontStyle.Bold);
            lblTituloSeccion.ForeColor = Color.Black;
            lblTituloSeccion.Location = new Point(25, 11);
            lblTituloSeccion.Name = "lblTituloSeccion";
            lblTituloSeccion.Size = new Size(640, 45);
            lblTituloSeccion.TabIndex = 0;
            lblTituloSeccion.Text = "Inicio";
            lblTituloSeccion.TextAlign = ContentAlignment.MiddleLeft;
            pnlContenido.BackColor = Color.White;
            pnlContenido.Dock = DockStyle.Fill;
            pnlContenido.Location = new Point(230, 65);
            pnlContenido.Name = "pnlContenido";
            pnlContenido.Size = new Size(690, 475);
            pnlContenido.TabIndex = 2;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(920, 540);
            Controls.Add(pnlContenido);
            Controls.Add(pnlEncabezado);
            Controls.Add(pnlMenuLateral);
            Font = new Font("Segoe UI", 9F);
            FormBorderStyle = FormBorderStyle.Sizable;
            MaximizeBox = true;
            MinimizeBox = true;
            MinimumSize = new Size(920, 540);
            Name = "FrmPrincipal";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Super Saija Gym";
            WindowState = FormWindowState.Normal;
            Load += FrmPrincipal_Load;
            pnlMenuLateral.ResumeLayout(false);
            pnlOpciones.ResumeLayout(false);
            pnlSesion.ResumeLayout(false);
            tlpBotonesSesion.ResumeLayout(false);
            pnlEncabezado.ResumeLayout(false);
            ResumeLayout(false);
        }

        private Panel pnlMenuLateral;
        private Label lblNombreSistema;
        private Panel pnlOpciones;
        private Button btnInicio;
        private Button btnClientes;
        private Button btnEntrenadores;
        private Button btnTiposMembresias;
        private Button btnClasesActividades;
        private Button btnHorariosClases;
        private Button btnCategoriasProductos;
        private Button btnProductos;
        private Button btnProveedores;
        private Panel pnlSesion;
        private TableLayoutPanel tlpBotonesSesion;
        private Label lblBienvenida;
        private Label lblRol;
        private Button btnCerrarSesion;
        private Button btnSalir;
        private Panel pnlEncabezado;
        private Label lblTituloSeccion;
        private Panel pnlContenido;
    }
}
